log:
  level: info
  production: true

api:
  http: ":9091" # 在该地址启动 api 接口。
  
include:
  - "/app/mosdns/dat_exec.yaml"
  - "/app/mosdns/dns.yaml"
  - "/app/mosdns/best_cdn.yaml"

plugins:
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches:
          - has_resp
        exec: accept

  - tag: fallback_remote
    type: fallback
    args:
      primary: forward_remote
      secondary: forward_easy
      threshold: 500           # 无响应回滚阈值。单位毫秒。默认 500 。
      always_standby: true     # 副可执行插件始终待命。  
       
  - tag: remote_sequence # forward 二选一
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote          # mosdns后置：Dnsmasq → clash → mosdns
      - exec: accept

  - tag: gfw_ip_sequence
    type: sequence
    args:
      - matches: # 污染ip
          - resp_ip $gfw_cidr
        exec: goto remote_sequence
      - matches: # 屏蔽ip
          - resp_ip 0.0.0.0 127.0.0.1 ::1
        exec: goto remote_sequence

  - tag: local_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_alidns # 这里推荐使用当地运营商dns
      - exec: jump gfw_ip_sequence
      - exec: jump change_cdn_ip
      - exec: accept # 有没有响应都终止，防止后续查询其他上游

  - tag: ali_sequence_jp # 阿里日本准确度高，腾讯美国准确度高
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: ecs 13.78.0.0
      - exec: $forward_alidns ali_doh 
      - exec: jump change_cdn_ip
      - exec: accept

  - tag: tencent_sequence_lax
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: ecs 151.101.196.0
      - exec: $forward_dnspod
      - exec: jump change_cdn_ip
      - exec: accept
      
  - tag: default_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_alidns # 默认用国内，用来查询是否污染
      - matches:
          - resp_ip $geoip_cn
        exec: accept # 国内直接接受
      - exec: jump gfw_ip_sequence
      - exec: drop_resp

  - tag: global_sequence_us
    type: sequence
    args:      
      - exec: ecs 151.101.196.0   # mosdns前置：走 US ECS 直连，删去 _US 代表国外全部走代理 # Los_Angeles
      - exec: $fallback_remote       # 也可以直接用 forward_remote
      - exec: jump change_cdn_ip  # mosdns后置：MATCH若走直连，才会用到remote_sequence_us
      - exec: jump has_resp_sequence

  - tag: fallback_final
    type: fallback
    args:
      primary: default_sequence       # 国内ip走直连，如果是gfw ip 走代理
      secondary: global_sequence_us   # 国外ip 尝试优选  走直连
      threshold: 360           # 无响应回滚阈值。单位毫秒。默认 500 。
      always_standby: true     # 副可执行插件始终待命。

  - tag: main_sequence
    type: sequence
    args:
      - matches:
          - qtype 65
        exec: reject 3 # 屏蔽 QTYPE 65

      - matches: 
          - qname dalamud.com
        exec: $forward_local
      - exec: jump has_resp_sequence

      # - matches:
      #     - qname &./rule/white_list.txt # DDNS 和 白名单
      #   exec: $forward_local
      # - exec: ttl 5-180 #如果使用了DDNS，把这个打开
      # - exec: jump has_resp_sequence

      - matches: "!qtype 1 28"
        exec: $forward_remote
      - matches: "!qtype 1 28" # = accept
        exec: accept
        
      - exec: $cache_0 # 下面的请求结果均进入缓存
      - exec: jump has_resp_sequence
      
      - matches:
          - qname $geosite_akamai
        exec: jump ali_sequence_jp

      - matches:
          - qname ebay.com # 占位
        exec: jump tencent_sequence_lax
        
      - matches:
          - qname apple.com edgesuite.net icloud.com live.com live.net msftconnecttest.com office365.com office.com outlook.com trafficmanager.net xbox.com
        exec: $forward_dnspod
      - exec: jump has_resp_sequence
      
      - matches:
          - qname $geosite_google-cn
        exec: jump remote_sequence # 适用于被墙/被污染/尚未移出geosite_cn列表的，提前走代理

      - matches:
          - qname $geosite_cn
        exec: jump local_sequence # 国内域名提前走直连
        
      - matches:
          - qname $geosite_gfw # GFW 域名直接走代理
        exec: jump remote_sequence
        
      - exec: $fallback_final # 不在列表内的域名
      
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :53