name: Auto Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check-update.outputs.tag }}
      status: ${{ steps.check-update.outputs.status }}
    steps:
      - name: Check Update
        id: check-update
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/IrineSistiana/mosdns/releases | jq -r '.[] | select(.prerelease == false) | .tag_name' | head -n 1)
          DOCKER_RELEASE_TAG=$(curl -s -X GET https://registry.hub.docker.com/v2/repositories/dalamudx/mosdns/tags/${RELEASE_TAG} | jq '.name')
          echo "Docker Release 版本: ${DOCKER_RELEASE_TAG}"
          echo "Git Release 版本: ${RELEASE_TAG}"
          if [ "${RELEASE_TAG}" != "" ]
          then
            if [ "${DOCKER_RELEASE_TAG}" == "null" ]
            then
                echo "tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
                echo "status=success" >> $GITHUB_OUTPUT
            else
              echo "status=fail" >> $GITHUB_OUTPUT
            fi
          else
              echo "status=fail" >> $GITHUB_OUTPUT
          fi

  build-docker:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.status != 'fail' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            TAG=${{ needs.check.outputs.tag }}
            REPOSITORY=IrineSistiana/mosdns
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns:${{ needs.check.outputs.tag }}