name: Manual Build Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        default: '5.3.3'
        description: "Specific the tag you want to build"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check-update.outputs.tag }}
      status: ${{ steps.check-update.outputs.status }}
    steps:
      - name: Check Update
        id: check-update
        run: |
          TAG=v${{ github.event.inputs.tag }}
          GIT_TAG=$(curl -s https://api.github.com/repos/IrineSistiana/mosdns/releases?per_page=100 | jq -r '.[] | .tag_name'|grep $TAG)
          DOCKER_TAG=$(curl -s -X GET https://registry.hub.docker.com/v2/repositories/dalamudx/mosdns/tags/${GIT_TAG} | jq '.name')
          echo "Docker 版本: ${DOCKER_TAG}"
          echo "Git Release 版本: ${GIT_TAG}"
          if [ "${GIT_TAG}" != "" ]
          then
            if [ "${DOCKER_TAG}" == "null" ]
            then
                echo "tag=${GIT_TAG}" >> $GITHUB_OUTPUT
                echo "status=success" >> $GITHUB_OUTPUT
            else
              echo "status=fail" >> $GITHUB_OUTPUT
            fi
          else
              echo "status=fail" >> $GITHUB_OUTPUT
          fi

  build-docker:
    if: ${{ needs.check.outputs.status != 'fail' }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            TAG=${{ needs.check.outputs.tag }}
            REPOSITORY=IrineSistiana/mosdns
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns:${{ needs.check.outputs.tag }}